# Generated by Django 4.1.5 on 2023-01-10 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_venta_articulo_venta_fecha_venta_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.articulos'),
        ),
    ]
